import api from "./api";
import { makeConfig } from "./api.config";

const getPlayers = async (
  key: string | unknown,
  leagueId: string,
  seasonId: string,
  teamId: string
): Promise<any> => {
  /*try {
    const response = await api.get(`/players?league=${leagueId}&season=${seasonId}&team=${teamId}`, makeConfig(key));
    return response.data;
  } catch (error) {
    throw new Error("Erro ao obter as temporadas");
  }*/
  const result = {
    get: "players",
    parameters: {
      league: "39",
      season: "2021",
      team: "33",
    },
    errors: [],
    results: 20,
    paging: {
      current: 1,
      total: 3,
    },
    response: [
      {
        player: {
          id: 883,
          name: "Lee Grant",
          firstname: "Lee",
          lastname: "Grant",
          age: 39,
          birth: {
            date: "1983-01-27",
            place: "Hemel Hempstead",
            country: "England",
          },
          nationality: "England",
          height: "193 cm",
          weight: "83 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/883.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Goalkeeper",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 0,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: null,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: null,
              missed: null,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 897,
          name: "M. Greenwood",
          firstname: "Mason Will John",
          lastname: "Greenwood",
          age: 21,
          birth: {
            date: "2001-10-01",
            place: "Bradford",
            country: "England",
          },
          nationality: "England",
          height: "181 cm",
          weight: "70 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/897.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 18,
              lineups: 16,
              minutes: 1281,
              number: null,
              position: "Attacker",
              rating: "7.044444",
              captain: false,
            },
            substitutes: {
              in: 2,
              out: 12,
              bench: 5,
            },
            shots: {
              total: 38,
              on: 19,
            },
            goals: {
              total: 5,
              conceded: 0,
              assists: 1,
              saves: null,
            },
            passes: {
              total: 464,
              key: 17,
              accuracy: 21,
            },
            tackles: {
              total: 15,
              blocks: null,
              interceptions: 1,
            },
            duels: {
              total: 131,
              won: 67,
            },
            dribbles: {
              attempts: 52,
              success: 32,
              past: null,
            },
            fouls: {
              drawn: 16,
              committed: 15,
            },
            cards: {
              yellow: 1,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 153429,
          name: "T. Mengi",
          firstname: "Teden Mambuene",
          lastname: "Mengi",
          age: 20,
          birth: {
            date: "2002-04-30",
            place: "Manchester",
            country: "England",
          },
          nationality: "England",
          height: "183 cm",
          weight: "78 kg",
          injured: false,
          photo: "https://media-2.api-sports.io/football/players/153429.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Defender",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 0,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: null,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: null,
              missed: null,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 284362,
          name: "B. Hardley",
          firstname: "Björn Bryan",
          lastname: "Hardley",
          age: 20,
          birth: {
            date: "2002-12-19",
            place: "Tilburg",
            country: "Netherlands",
          },
          nationality: "Netherlands",
          height: "189 cm",
          weight: null,
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/284362.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Defender",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 0,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: null,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: null,
              missed: null,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 180560,
          name: "H. Mejbri",
          firstname: "Hannibal",
          lastname: "Mejbri",
          age: 20,
          birth: {
            date: "2003-01-21",
            place: null,
            country: "France",
          },
          nationality: "Tunisia",
          height: "177 cm",
          weight: "74 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/180560.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 2,
              lineups: 1,
              minutes: 68,
              number: null,
              position: "Midfielder",
              rating: "6.250000",
              captain: false,
            },
            substitutes: {
              in: 1,
              out: 1,
              bench: 6,
            },
            shots: {
              total: 1,
              on: 1,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 21,
              key: null,
              accuracy: 8,
            },
            tackles: {
              total: 2,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: 9,
              won: 3,
            },
            dribbles: {
              attempts: 2,
              success: 1,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: 3,
            },
            cards: {
              yellow: 2,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 157997,
          name: "A. Diallo",
          firstname: "Amad",
          lastname: "Diallo Traoré",
          age: 21,
          birth: {
            date: "2002-07-11",
            place: "Abidjan",
            country: "Côte d'Ivoire",
          },
          nationality: "Côte d'Ivoire",
          height: "173 cm",
          weight: "72 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/157997.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Attacker",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 1,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 284300,
          name: "Álvaro Fernández",
          firstname: "Álvaro",
          lastname: "Fernández Carreras",
          age: 20,
          birth: {
            date: "2003-03-23",
            place: null,
            country: "Spain",
          },
          nationality: "Spain",
          height: null,
          weight: null,
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/284300.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Defender",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 4,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 284323,
          name: "C. Savage",
          firstname: "Charlie William Henry",
          lastname: "Savage",
          age: 20,
          birth: {
            date: "2003-05-02",
            place: "Leicester",
            country: "Wales",
          },
          nationality: "Wales",
          height: "182 cm",
          weight: "74 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/284323.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Midfielder",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 1,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 163054,
          name: "S. Shoretire",
          firstname: "Shola",
          lastname: "Maxwell Shoretire",
          age: 19,
          birth: {
            date: "2004-02-02",
            place: "Newcastle",
            country: "Nigeria",
          },
          nationality: "England",
          height: "170 cm",
          weight: "70 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/163054.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 1,
              lineups: 0,
              minutes: 15,
              number: null,
              position: "Attacker",
              rating: "6.700000",
              captain: false,
            },
            substitutes: {
              in: 1,
              out: 0,
              bench: 2,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 5,
              key: null,
              accuracy: 5,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: 1,
              won: 1,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: 1,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 874,
          name: "Cristiano Ronaldo",
          firstname: "Cristiano Ronaldo",
          lastname: "dos Santos Aveiro",
          age: 38,
          birth: {
            date: "1985-02-05",
            place: "Funchal",
            country: "Portugal",
          },
          nationality: "Portugal",
          height: "187 cm",
          weight: "83 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/874.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-3.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 30,
              lineups: 27,
              minutes: 2459,
              number: null,
              position: "Attacker",
              rating: "7.260000",
              captain: false,
            },
            substitutes: {
              in: 3,
              out: 6,
              bench: 3,
            },
            shots: {
              total: 80,
              on: 43,
            },
            goals: {
              total: 18,
              conceded: 0,
              assists: 3,
              saves: null,
            },
            passes: {
              total: 879,
              key: 26,
              accuracy: 24,
            },
            tackles: {
              total: 8,
              blocks: null,
              interceptions: 2,
            },
            duels: {
              total: 217,
              won: 88,
            },
            dribbles: {
              attempts: 32,
              success: 20,
              past: null,
            },
            fouls: {
              drawn: 18,
              committed: 16,
            },
            cards: {
              yellow: 8,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 3,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 885,
          name: "E. Bailly",
          firstname: "Eric Bertrand",
          lastname: "Bailly",
          age: 29,
          birth: {
            date: "1994-04-12",
            place: "Bingerville",
            country: "Côte d'Ivoire",
          },
          nationality: "Côte d'Ivoire",
          height: "187 cm",
          weight: "77 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/885.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 4,
              lineups: 3,
              minutes: 218,
              number: null,
              position: "Defender",
              rating: "6.600000",
              captain: false,
            },
            substitutes: {
              in: 1,
              out: 2,
              bench: 18,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 85,
              key: null,
              accuracy: 17,
            },
            tackles: {
              total: 5,
              blocks: 2,
              interceptions: 3,
            },
            duels: {
              total: 18,
              won: 11,
            },
            dribbles: {
              attempts: 1,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: 2,
            },
            cards: {
              yellow: 1,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 378,
          name: "Alex Telles",
          firstname: "Alex",
          lastname: "Nicolao Telles",
          age: 31,
          birth: {
            date: "1992-12-15",
            place: "Caxias do Sul",
            country: "Brazil",
          },
          nationality: "Brazil",
          height: "181 cm",
          weight: "71 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/378.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 21,
              lineups: 18,
              minutes: 1659,
              number: null,
              position: "Defender",
              rating: "6.985714",
              captain: false,
            },
            substitutes: {
              in: 3,
              out: 2,
              bench: 11,
            },
            shots: {
              total: 7,
              on: 3,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: 4,
              saves: null,
            },
            passes: {
              total: 935,
              key: 26,
              accuracy: 35,
            },
            tackles: {
              total: 48,
              blocks: 4,
              interceptions: 26,
            },
            duels: {
              total: 181,
              won: 99,
            },
            dribbles: {
              attempts: 22,
              success: 12,
              past: null,
            },
            fouls: {
              drawn: 9,
              committed: 23,
            },
            cards: {
              yellow: 1,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 274,
          name: "E. Cavani",
          firstname: "Edinson Roberto",
          lastname: "Cavani Gómez",
          age: 36,
          birth: {
            date: "1987-02-14",
            place: "Salto",
            country: "Uruguay",
          },
          nationality: "Uruguay",
          height: "184 cm",
          weight: "71 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/274.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-3.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 15,
              lineups: 7,
              minutes: 762,
              number: null,
              position: "Attacker",
              rating: "6.620000",
              captain: false,
            },
            substitutes: {
              in: 8,
              out: 3,
              bench: 8,
            },
            shots: {
              total: 14,
              on: 8,
            },
            goals: {
              total: 2,
              conceded: 0,
              assists: 1,
              saves: null,
            },
            passes: {
              total: 230,
              key: 7,
              accuracy: 11,
            },
            tackles: {
              total: 4,
              blocks: null,
              interceptions: 2,
            },
            duels: {
              total: 55,
              won: 20,
            },
            dribbles: {
              attempts: 5,
              success: 4,
              past: null,
            },
            fouls: {
              drawn: 5,
              committed: 7,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 901,
          name: "Mata",
          firstname: "Juan Manuel",
          lastname: "Mata García",
          age: 35,
          birth: {
            date: "1988-04-28",
            place: "Burgos",
            country: "Spain",
          },
          nationality: "Spain",
          height: "170 cm",
          weight: "63 kg",
          injured: false,
          photo: "https://media-2.api-sports.io/football/players/901.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-3.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 7,
              lineups: 2,
              minutes: 232,
              number: null,
              position: "Midfielder",
              rating: "6.771428",
              captain: false,
            },
            substitutes: {
              in: 5,
              out: 2,
              bench: 27,
            },
            shots: {
              total: 3,
              on: 1,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 208,
              key: 2,
              accuracy: 26,
            },
            tackles: {
              total: 6,
              blocks: null,
              interceptions: 1,
            },
            duels: {
              total: 22,
              won: 13,
            },
            dribbles: {
              attempts: 6,
              success: 3,
              past: null,
            },
            fouls: {
              drawn: 4,
              committed: 2,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 882,
          name: "David de Gea",
          firstname: "David",
          lastname: "de Gea Quintana",
          age: 33,
          birth: {
            date: "1990-11-07",
            place: "Madrid",
            country: "Spain",
          },
          nationality: "Spain",
          height: "192 cm",
          weight: "76 kg",
          injured: false,
          photo: "https://media-2.api-sports.io/football/players/882.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-3.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 38,
              lineups: 38,
              minutes: 3420,
              number: null,
              position: "Goalkeeper",
              rating: "6.860526",
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 0,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 57,
              assists: null,
              saves: 128,
            },
            passes: {
              total: 788,
              key: null,
              accuracy: 14,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: 9,
              won: 9,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: 1,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: 0,
            },
          },
        ],
      },
      {
        player: {
          id: 2931,
          name: "T. Heaton",
          firstname: "Thomas David",
          lastname: "Heaton",
          age: 37,
          birth: {
            date: "1986-04-15",
            place: "Chester",
            country: "England",
          },
          nationality: "England",
          height: "188 cm",
          weight: "85 kg",
          injured: false,
          photo: "https://media-2.api-sports.io/football/players/2931.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 0,
              lineups: 0,
              minutes: 0,
              number: null,
              position: "Goalkeeper",
              rating: null,
              captain: false,
            },
            substitutes: {
              in: 0,
              out: 0,
              bench: 14,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: null,
              key: null,
              accuracy: null,
            },
            tackles: {
              total: null,
              blocks: null,
              interceptions: null,
            },
            duels: {
              total: null,
              won: null,
            },
            dribbles: {
              attempts: null,
              success: null,
              past: null,
            },
            fouls: {
              drawn: null,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: 0,
            },
          },
        ],
      },
      {
        player: {
          id: 889,
          name: "V. Lindelöf",
          firstname: "Victor Jörgen",
          lastname: "Nilsson Lindelöf",
          age: 29,
          birth: {
            date: "1994-07-17",
            place: "Västerås",
            country: "Sweden",
          },
          nationality: "Sweden",
          height: "187 cm",
          weight: "80 kg",
          injured: false,
          photo: "https://media-3.api-sports.io/football/players/889.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-1.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-1.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 28,
              lineups: 26,
              minutes: 2355,
              number: null,
              position: "Defender",
              rating: "6.767857",
              captain: false,
            },
            substitutes: {
              in: 2,
              out: 1,
              bench: 7,
            },
            shots: {
              total: 2,
              on: 2,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: 2,
              saves: null,
            },
            passes: {
              total: 1377,
              key: 4,
              accuracy: 43,
            },
            tackles: {
              total: 16,
              blocks: 17,
              interceptions: 25,
            },
            duels: {
              total: 134,
              won: 77,
            },
            dribbles: {
              attempts: 3,
              success: 3,
              past: null,
            },
            fouls: {
              drawn: 6,
              committed: 19,
            },
            cards: {
              yellow: 4,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 888,
          name: "P. Jones",
          firstname: "Phil Anthony",
          lastname: "Jones",
          age: 31,
          birth: {
            date: "1992-02-21",
            place: "Preston",
            country: "England",
          },
          nationality: "England",
          height: "180 cm",
          weight: "71 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/888.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-2.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-2.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 4,
              lineups: 2,
              minutes: 162,
              number: null,
              position: "Defender",
              rating: "6.800000",
              captain: false,
            },
            substitutes: {
              in: 2,
              out: 1,
              bench: 22,
            },
            shots: {
              total: null,
              on: null,
            },
            goals: {
              total: 0,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 81,
              key: null,
              accuracy: 17,
            },
            tackles: {
              total: 5,
              blocks: 4,
              interceptions: 3,
            },
            duels: {
              total: 11,
              won: 10,
            },
            dribbles: {
              attempts: 1,
              success: 1,
              past: null,
            },
            fouls: {
              drawn: 2,
              committed: null,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 2935,
          name: "H. Maguire",
          firstname: "Jacob Harry",
          lastname: "Maguire",
          age: 30,
          birth: {
            date: "1993-03-05",
            place: "Sheffield",
            country: "England",
          },
          nationality: "England",
          height: "194 cm",
          weight: "90 kg",
          injured: false,
          photo: "https://media-2.api-sports.io/football/players/2935.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-3.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-3.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 30,
              lineups: 28,
              minutes: 2514,
              number: null,
              position: "Defender",
              rating: "6.926666",
              captain: false,
            },
            substitutes: {
              in: 2,
              out: 1,
              bench: 5,
            },
            shots: {
              total: 19,
              on: 10,
            },
            goals: {
              total: 1,
              conceded: 0,
              assists: null,
              saves: null,
            },
            passes: {
              total: 1563,
              key: 4,
              accuracy: 45,
            },
            tackles: {
              total: 34,
              blocks: 29,
              interceptions: 32,
            },
            duels: {
              total: 199,
              won: 132,
            },
            dribbles: {
              attempts: 5,
              success: 4,
              past: null,
            },
            fouls: {
              drawn: 19,
              committed: 21,
            },
            cards: {
              yellow: 8,
              yellowred: 1,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
      {
        player: {
          id: 742,
          name: "R. Varane",
          firstname: "Raphaël Xavier",
          lastname: "Varane",
          age: 30,
          birth: {
            date: "1993-04-25",
            place: "Lille",
            country: "France",
          },
          nationality: "France",
          height: "191 cm",
          weight: "81 kg",
          injured: false,
          photo: "https://media-1.api-sports.io/football/players/742.png",
        },
        statistics: [
          {
            team: {
              id: 33,
              name: "Manchester United",
              logo: "https://media-3.api-sports.io/football/teams/33.png",
            },
            league: {
              id: 39,
              name: "Premier League",
              country: "England",
              logo: "https://media-2.api-sports.io/football/leagues/39.png",
              flag: "https://media-1.api-sports.io/flags/gb.svg",
              season: 2021,
            },
            games: {
              appearences: 22,
              lineups: 20,
              minutes: 1829,
              number: null,
              position: "Defender",
              rating: "6.950000",
              captain: false,
            },
            substitutes: {
              in: 2,
              out: 0,
              bench: 4,
            },
            shots: {
              total: 6,
              on: 1,
            },
            goals: {
              total: 1,
              conceded: 0,
              assists: 1,
              saves: null,
            },
            passes: {
              total: 1151,
              key: 4,
              accuracy: 48,
            },
            tackles: {
              total: 28,
              blocks: 9,
              interceptions: 18,
            },
            duels: {
              total: 130,
              won: 92,
            },
            dribbles: {
              attempts: 3,
              success: 2,
              past: null,
            },
            fouls: {
              drawn: 7,
              committed: 5,
            },
            cards: {
              yellow: 0,
              yellowred: 0,
              red: 0,
            },
            penalty: {
              won: null,
              commited: null,
              scored: 0,
              missed: 0,
              saved: null,
            },
          },
        ],
      },
    ],
  };
  return result.response;
};

export default getPlayers;
